version: '3'
services:
  n1:
    build: .
    image: cassandra-with-cqlshrc
    networks:
      - cluster
    environment:
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
  n2:
    image: cassandra-with-cqlshrc
    networks:
      - cluster
    environment:
      - CASSANDRA_SEEDS=n1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
    depends_on:
      - n1
  n3:
    image: cassandra-with-cqlshrc
    networks:
      - cluster
    environment:
      - CASSANDRA_SEEDS=n1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC2
    depends_on:
      - n1
  n4:
    image: cassandra-with-cqlshrc
    networks:
      - cluster
    environment:
      - CASSANDRA_SEEDS=n1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=RAC1
    depends_on:
      - n1
networks:
  cluster:
